# nb@2025.05.28

"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$time\
$line_break\
$sudo\
$character\
"""

add_newline = false

[line_break]
disabled = false

[fill]
symbol = "─"
style = "bright-white"

[character]
success_symbol = "[❭❭](bold white)"
error_symbol = "[❭❭](bold red)"

[os]
format = "[ $symbol ]($style)"
disabled = false
style = "bg:green fg:black"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[directory]
truncation_length = 4
truncation_symbol = "…/"
home_symbol = "~"
read_only = ""
format = "[ $path$read_only ]($style)"
style = "bg:bright-blue fg:bold bright-white"

[username]
style_user = "bg:yellow fg:black"
style_root = "bright-red bold"
format = "[ $user ]($style)"
disabled = false
show_always = true

[git_status]
format = '([\[$all_status$ahead_behind\] ]($style))'
style = "fg:black bg:cyan"

[git_branch]
symbol = ""
style = "fg:black bg:cyan"
format = '[ $symbol $branch ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:bright-purple fg:bright-white"
format = '[ $time ]($style)'

[sudo]
format = "[ $symbol]($style)"
style = "bg:bright-red fg:bold white"
symbol = "⚡"
disabled = false

[hostname]
ssh_only = false
format = "[ $hostname ]($style)"
style = "fg:bright-white bg:bright-red"
disabled = false
