# nb@2025.05.30

# //////////// HELIX THEME: MODERN (Inherits Base16 Terminal) ///////////

inherits = "base16_terminal"


# /////////// STATUSLINE ///////////

"ui.statusline" = { fg = "yellow", bg = "black" }
"ui.statusline.inactive" = { fg = "gray", bg = "black" }
"ui.statusline.separator" = { fg = "gray", bg = "black" }


# /////////// MODES ///////////

"ui.statusline.normal" = { bg = "light-blue", fg = "black", modifiers = [
  "bold",
] }
"ui.statusline.insert" = { bg = "light-red", fg = "black", modifiers = [
  "bold",
] }
"ui.statusline.select" = { bg = "light-magenta", fg = "black", modifiers = [
  "bold",
] }


# /////////// MENUS & POPUPS ///////////

"ui.menu" = { bg = "black", fg = "white" }
"ui.menu.selected" = { bg = "yellow", fg = "black", modifiers = ["bold"] }
"ui.popup" = { bg = "black", fg = "white" }
"ui.popup.info" = { bg = "black", fg = "yellow" }
"ui.window" = { bg = "black" }
"ui.help" = { bg = "black", fg = "white" }


# /////////// DIAGNOSTICS ///////////

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "green", style = "curl" } }


# /////////// BUFFERLINE ///////////

"ui.bufferline.active" = { fg = "yellow", bg = "black", modifiers = ["bold"] }
"ui.bufferline" = { fg = "gray", bg = "black" }
"ui.bufferline.background" = { bg = "black" }


# /////////// SYNTAX ///////////

"ui.selection.primary" = { bg = "#8f0086", fg = "white" }
"operator" = { fg = "red" }
"keyword.control.return" = { fg = "red" }
"keyword.control.exception" = { fg = "red", modifiers = ["bold"] }
"keyword.control.repeat" = { fg = "#cfd89c", modifiers = ["italic"] }
"string.special.symbol" = { fg = "magenta" }
"variable.builtin" = { fg = "white", modifiers = ["italic"] }
